### PR TITLE
fix(forms): reset multiple models (#210)

### LINKED ISSUE #210: the form won't reset in case of multiple fieldsets
There is a bug, we should reset all fieldset, currently, only the first one is resetting. 

https://github.com/TYPO3-Initiatives/nuxt-typo3/blob/6732410ef078db509cf3df5b76b058be526f81bf/lib/components/T3Form/T3FormFieldList/T3FormFieldList.vue#L117

Additionally, there is a but when fieldset has 0 elements - we should not render form list

### PR DESCRIPTION
**Pull request by mercs600**
resolve #210

### CODE REVIEW

File: lib/components/T3Form/T3FormFieldList/T3FormFieldList.vue [hunk 1]
```diff
@@ -11,7 +11,7 @@
         :field="field"
       >
         <T3FormFieldList
-          v-if="field.fieldlist"
+          v-if="field.fieldlist && field.elements"
```
Comment (gdulamat) [inline lib/components/T3Form/T3FormFieldList/T3FormFieldList.vue:14]: `field.elements` is an array, so this condition will be truthy even when an array will be empty; I suggest adding `.length` like in the `restoreModel` method.

**Review by gdulamat — COMMENTED** [review]
Good job! 🎉

File: lib/components/T3Form/T3FormFieldList/T3FormFieldList.vue (hunk 1 above)
Comment (mercs600) [reply lib/components/T3Form/T3FormFieldList/T3FormFieldList.vue:14]: in that case, API doesn't deliver an empty array, in the case of 0 elements API doesn't deliver elements field at all :D the empty array is not an issue, but the lack of this field is :D However, I can agree we don't have to render this component in case of the empty array - at least for now 👍
